repos:
  # Pre-commit hooks for basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Basic file checks
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

      # Python specific
      - id: debug-statements
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: requirements-txt-fixer

  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # isort import sorter
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "88"]

  # flake8 linter
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, flake8-import-order]
        args: [--max-line-length=88, --extend-ignore=E203,W503,E501]

  # mypy type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, types-toml]
        args: [--strict, --ignore-missing-imports]
        files: ^src/

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: Dockerfile.*

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml]
        exclude: \.gitlab-ci\.yml$

  # Spell checking
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [--write-changes]
        exclude: ^(.*\.lock|CHANGELOG\.md)$

  # Local hooks for project-specific checks
  - repo: local
    hooks:
      # DoMD self-check
      - id: domd-health-check
        name: DoMD Self Health Check
        entry: poetry run domd --dry-run --quiet
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]

      # Check version consistency
      - id: version-check
        name: Version Consistency Check
        entry: python scripts/check_version.py
        language: system
        files: ^(pyproject\.toml|src/domd/__init__\.py|CHANGELOG\.md)$

      # Test coverage check
      - id: coverage-check
        name: Test Coverage Check
        entry: poetry run pytest --cov=domd --cov-fail-under=80 --quiet
        language: system
        pass_filenames: false
        stages: [push]

      # Documentation links check
      - id: doc-links-check
        name: Documentation Links Check
        entry: python scripts/check_doc_links.py
        language: system
        files: ^(README\.md|docs/.*\.md)$

# Configuration for different stages
default_stages: [commit]

# Specific stage configurations
stages:
  - commit
  - push
  - manual

# CI configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false

# Exclude patterns
exclude: |
  (?x)^(
      \.git/.*|
      \.tox/.*|
      \.venv/.*|
      build/.*|
      dist/.*|
      .*\.egg-info/.*|
      __pycache__/.*|
      \.pytest_cache/.*|
      \.mypy_cache/.*|
      htmlcov/.*|
      site/.*|
      examples/.*\.generated\..*
  )$
